import React, { useReducer, useEffect, useRef, useCallback, useMemo } from "react";
import { Textarea } from "@/components/ui/textarea";
import { ArrowLeft, Loader2, Sparkles, CheckCircle2, Info, Bookmark, X } from "lucide-react";
import { suggestWorkExperienceBullets, parseProfileFromImport } from "@/services/geminiService";
import { useUserProfile } from "@/context/UserProfileContext";
import { parseDocumentToText } from "@/services/documentParserService";
import { buildResumeDocumentFromText, ResumeImportError } from "@/services/resumeImportService";
import { resumeFormReducer, makeInitialState } from "./resumeFormReducer";
import { PersonalInfoSection } from "./PersonalInfoSection";
import { WorkHistorySection } from "./WorkHistorySection";
import { EducationSection } from "./EducationSection";
import { SkillsSection, getSkillsForRoles } from "./SkillsSection";
import { TemplatePicker } from "./TemplatePicker";
import { ImportSection } from "./ImportSection";
import { Step0StartMethod } from "./Step0StartMethod";

const DRAFT_KEY = "resume_builder_draft";

export function ResumeGenerationForm({ onSubmit, isGenerating, onAnalyze, onTailor, onImportToEditor }: { onSubmit: (data: any) => void; isGenerating: boolean; onAnalyze?: (resumeText: string, file: File) => void; onTailor?: (resumeText: string, resumeName: string) => void; onImportToEditor?: (markdown: string) => void }) {
  const { profile, loading } = useUserProfile();
  const [state, dispatch] = useReducer(resumeFormReducer, profile, makeInitialState);
  const formRootRef = useRef<HTMLDivElement>(null);
  const profileLoadedRef = useRef(false);
  const saveTimer = useRef<ReturnType<typeof setTimeout> | null>(null);

  const { step, template, targetRoleSelect, targetRole, personalInfo, workHistory, education, skills, newSkill, jobDescription, profileBannerDismissed, profileWasUsed, autoGeneratedEntries, autoGeneratingEntries, isGeneratingBullets, showImport, importText, importType, isImporting, importError, expandedWorkIndices, expandedEduIndices, suggestedSkills, draftBannerDismissed, hasDraft, uploadedResumeText, uploadedFileName, step0Uploading, step0Error, step0ResumeUploaded, processingChoice, startMethod } = state;

  // Scroll to top when step changes
  useEffect(() => {
    let el = formRootRef.current?.parentElement ?? null;
    while (el) {
      if (el.scrollHeight > el.clientHeight) { el.scrollTop = 0; break; }
      el = el.parentElement;
    }
  }, [step]);

  // Check for draft on mount
  useEffect(() => {
    try {
      const raw = localStorage.getItem(DRAFT_KEY);
      if (raw) dispatch({ type: "SET_HAS_DRAFT", payload: true });
    } catch {}
  }, []);

  // Once profile finishes loading, back-fill empty fields
  useEffect(() => {
    if (loading || profileLoadedRef.current) return;
    profileLoadedRef.current = true;
    const hasProfileData = !!(profile.workHistory?.length || profile.fullName || profile.email);
    if (!personalInfo.name && !personalInfo.email) {
      dispatch({ type: "SET_PERSONAL_INFO", payload: { name: profile.fullName ?? "", email: profile.email ?? "", phone: profile.phone ?? "", linkedin: profile.linkedin ?? "", github: profile.github ?? "", portfolio: profile.portfolio ?? "" } });
    }
    if (workHistory.length === 1 && !workHistory[0].company && !workHistory[0].role && profile.workHistory?.length) {
      const mapped = profile.workHistory.map(({ company, role, startDate, endDate, responsibilities, current }) => ({ company, role, startDate, endDate, responsibilities, current: Boolean(current) }));
      dispatch({ type: "SET_WORK_HISTORY", payload: mapped });
      dispatch({ type: "SET_EXPANDED_WORK_INDICES", payload: mapped.map((_, i) => i) });
    }
    if (education.length === 1 && !education[0].university && profile.education?.length) {
      const mapped = profile.education.map(({ university, degree, graduationYear, major, minor }) => ({ university, degree, graduationYear, major: major ?? "", minor: minor ?? "" }));
      dispatch({ type: "SET_EDUCATION", payload: mapped });
      dispatch({ type: "SET_EXPANDED_EDU_INDICES", payload: mapped.map((_, i) => i) });
    }
    if (skills.length === 0 && profile.skills?.length) dispatch({ type: "SET_SKILLS", payload: profile.skills });
    if (!targetRole && profile.targetRole) {
      dispatch({ type: "SET_TARGET_ROLE_SELECT", payload: "Other" });
      dispatch({ type: "SET_TARGET_ROLE", payload: profile.targetRole });
    }
    if (hasProfileData) dispatch({ type: "SET_PROFILE_WAS_USED", payload: true });
  }, [loading]);

  // Auto-suggest bullets after profile loads for entries with role but no responsibilities
  useEffect(() => {
    if (loading) return;
    const effectiveRole = targetRoleSelect === "Other" ? targetRole : targetRoleSelect;
    if (!effectiveRole) return;
    workHistory.forEach((work, idx) => {
      if (work.role && !work.responsibilities && !autoGeneratedEntries.includes(idx) && !autoGeneratingEntries.includes(idx)) {
        const newAutoGenerating = [...autoGeneratingEntries, idx];
        dispatch({ type: "SET_AUTO_GENERATING_ENTRIES", payload: newAutoGenerating });
        const snapshot = workHistory;
        suggestWorkExperienceBullets(work.role, work.company)
          .then((suggestions) => {
            const updated = [...snapshot];
            if (!updated[idx].responsibilities) updated[idx] = { ...updated[idx], responsibilities: suggestions };
            dispatch({ type: "SET_WORK_HISTORY", payload: updated });
            dispatch({ type: "SET_AUTO_GENERATED_ENTRIES", payload: [...autoGeneratedEntries, idx] });
          })
          .catch(() => {})
          .finally(() => { dispatch({ type: "SET_AUTO_GENERATING_ENTRIES", payload: newAutoGenerating.filter((i) => i !== idx) }); });
      }
    });
  }, [loading, targetRole, targetRoleSelect]);

  // Update suggested skills when work history changes
  useEffect(() => {
    dispatch({ type: "SET_SUGGESTED_SKILLS", payload: getSkillsForRoles(workHistory.map((w) => w.role)) });
  }, [workHistory]);

  // Debounced save draft to localStorage
  useEffect(() => {
    if (!profileLoadedRef.current) return;
    if (saveTimer.current) clearTimeout(saveTimer.current);
    saveTimer.current = setTimeout(() => {
      try { localStorage.setItem(DRAFT_KEY, JSON.stringify({ targetRole, targetRoleSelect, jobDescription, template })); } catch {}
    }, 500);
    return () => { if (saveTimer.current) clearTimeout(saveTimer.current); };
  }, [targetRole, targetRoleSelect, jobDescription, template]);

  const restoreDraft = useCallback(() => {
    try {
      const raw = localStorage.getItem(DRAFT_KEY);
      if (!raw) return;
      const d = JSON.parse(raw);
      if (d.targetRole) dispatch({ type: "SET_TARGET_ROLE", payload: d.targetRole });
      if (d.targetRoleSelect) dispatch({ type: "SET_TARGET_ROLE_SELECT", payload: d.targetRoleSelect });
      if (d.jobDescription) dispatch({ type: "SET_JOB_DESCRIPTION", payload: d.jobDescription });
      if (d.template) dispatch({ type: "SET_TEMPLATE", payload: d.template });
    } catch {}
    dispatch({ type: "SET_HAS_DRAFT", payload: false });
    dispatch({ type: "SET_DRAFT_BANNER_DISMISSED", payload: true });
  }, []);

  const handleFileUpload = async (e: React.ChangeEvent<HTMLInputElement>, type: "linkedin" | "resume") => {
    const file = e.target.files?.[0];
    if (!file) return;
    dispatch({ type: "SET_IMPORT_ERROR", payload: null });
    dispatch({ type: "SET_IS_IMPORTING", payload: true });
    try {
      const text = await parseDocumentToText(file);
      if (text.trim().length < 100) {
        dispatch({ type: "SET_IMPORT_ERROR", payload: "Could not extract enough text. Try pasting the text manually." });
        dispatch({ type: "SET_IS_IMPORTING", payload: false });
        return;
      }
      await runImport(text, type);
    } catch (err) {
      const msg = err instanceof Error ? err.message : String(err);
      dispatch({ type: "SET_IMPORT_ERROR", payload: `Failed to read file: ${msg}. Try pasting the text manually.` });
      dispatch({ type: "SET_IS_IMPORTING", payload: false });
    }
  };

  const runImport = async (text: string, type: "linkedin" | "resume") => {
    dispatch({ type: "SET_IS_IMPORTING", payload: true });
    try {
      const parsed = await parseProfileFromImport({ type, text });
      const str = (v: unknown) => (v == null ? "" : String(v));
      if (parsed.fullName) dispatch({ type: "SET_PERSONAL_INFO", payload: { name: str(parsed.fullName) || personalInfo.name, email: str(parsed.email) || personalInfo.email, phone: str(parsed.phone) || personalInfo.phone, linkedin: str(parsed.linkedin) || personalInfo.linkedin, github: str(parsed.github) || personalInfo.github, portfolio: str(parsed.portfolio) || personalInfo.portfolio } });
      if (parsed.workHistory?.length) {
        const mapped = parsed.workHistory.map((w) => ({ company: str(w.company), role: str(w.role), startDate: str(w.startDate), endDate: str(w.endDate), responsibilities: str(w.responsibilities), current: Boolean((w as { current?: boolean }).current) }));
        dispatch({ type: "SET_WORK_HISTORY", payload: mapped });
        dispatch({ type: "SET_EXPANDED_WORK_INDICES", payload: mapped.map((_, i) => i) });
      }
      if (parsed.education?.length) {
        const mapped = parsed.education.map((e) => ({ university: str(e.university), degree: str(e.degree), graduationYear: str(e.graduationYear), major: str(e.major), minor: str(e.minor) }));
        dispatch({ type: "SET_EDUCATION", payload: mapped });
        dispatch({ type: "SET_EXPANDED_EDU_INDICES", payload: mapped.map((_, i) => i) });
      }
      if (parsed.skills?.length) dispatch({ type: "SET_SKILLS", payload: parsed.skills });
      if (parsed.targetRole) { dispatch({ type: "SET_TARGET_ROLE_SELECT", payload: "Other" }); dispatch({ type: "SET_TARGET_ROLE", payload: parsed.targetRole }); }
      dispatch({ type: "SET_SHOW_IMPORT", payload: false });
      dispatch({ type: "SET_IMPORT_TEXT", payload: "" });
    } catch (err) {
      dispatch({ type: "SET_IMPORT_ERROR", payload: "Failed to parse the content. Please try again." });
    } finally {
      dispatch({ type: "SET_IS_IMPORTING", payload: false });
    }
  };

  const handleStep0Upload = async (e: React.ChangeEvent<HTMLInputElement>, type: "linkedin" | "resume") => {
    const file = e.target.files?.[0];
    if (!file) return;
    dispatch({ type: "SET_STEP0_ERROR", payload: null });
    dispatch({ type: "SET_STEP0_UPLOADING", payload: type });
    try {
      const text = await parseDocumentToText(file);
      if (text.trim().length < 100) { dispatch({ type: "SET_STEP0_ERROR", payload: "Could not extract enough text from this file." }); return; }
      if (type === "resume") { dispatch({ type: "SET_STEP0_RESUME_UPLOADED", payload: { text, fileName: file.name, file } }); return; }
      const { markdown } = await buildResumeDocumentFromText(text, undefined, "linkedin");
      onImportToEditor?.(markdown);
    } catch (err) {
      dispatch({ type: "SET_STEP0_ERROR", payload: err instanceof ResumeImportError ? err.message : "Failed to read file. Please try again." });
    } finally {
      dispatch({ type: "SET_STEP0_UPLOADING", payload: null });
      if (e.target) e.target.value = "";
    }
  };

  const handleImport = async () => {
    if (!importText.trim()) return;
    await runImport(importText.trim(), importType);
  };

  const handleResumeChoice = async (choice: "analyze" | "tailor" | "editor") => {
    if (!step0ResumeUploaded || processingChoice) return;
    dispatch({ type: "SET_STEP0_ERROR", payload: null });
    dispatch({ type: "SET_PROCESSING_CHOICE", payload: choice });
    try {
      const { markdown } = await buildResumeDocumentFromText(step0ResumeUploaded.text);
      if (choice === "analyze") onAnalyze?.(markdown, step0ResumeUploaded.file);
      else if (choice === "tailor") onTailor?.(markdown, step0ResumeUploaded.fileName.replace(/\.[^.]+$/, ""));
      else onImportToEditor?.(markdown);
      dispatch({ type: "SET_STEP0_RESUME_UPLOADED", payload: null });
    } catch (err) {
      dispatch({ type: "SET_STEP0_ERROR", payload: err instanceof ResumeImportError ? err.message : "Couldn't import this resume. Please try again." });
    } finally {
      dispatch({ type: "SET_PROCESSING_CHOICE", payload: null });
    }
  };

  const handleSubmit = (e: React.FormEvent) => {
    e.preventDefault();
    try { localStorage.removeItem(DRAFT_KEY); } catch {}
    onSubmit({ template, targetRole: targetRoleSelect === "Other" ? targetRole : targetRoleSelect, personalInfo, workHistory, education, skills: skills.join(", "), jobDescription, uploadedResumeText });
  };

  const step0State = useMemo(() => ({ startMethod, step0Uploading, step0Error, step0ResumeUploaded, processingChoice }), [startMethod, step0Uploading, step0Error, step0ResumeUploaded, processingChoice]);
  const templatePickerState = useMemo(() => ({ template, uploadedResumeText, uploadedFileName }), [template, uploadedResumeText, uploadedFileName]);
  const personalInfoState = useMemo(() => ({ personalInfo, targetRole, targetRoleSelect, template }), [personalInfo, targetRole, targetRoleSelect, template]);
  const workHistoryState = useMemo(() => ({ workHistory, expandedWorkIndices, autoGeneratedEntries, autoGeneratingEntries, isGeneratingBullets, targetRole, targetRoleSelect }), [workHistory, expandedWorkIndices, autoGeneratedEntries, autoGeneratingEntries, isGeneratingBullets, targetRole, targetRoleSelect]);
  const educationState = useMemo(() => ({ education, expandedEduIndices }), [education, expandedEduIndices]);
  const skillsState = useMemo(() => ({ skills, newSkill, suggestedSkills, targetRole }), [skills, newSkill, suggestedSkills, targetRole]);
  const importSectionState = useMemo(() => ({ showImport, importText, importType, isImporting, importError }), [showImport, importText, importType, isImporting, importError]);

  if (step === 0) {
    return (
      <Step0StartMethod
        state={step0State}
        dispatch={dispatch}
        onStep0Upload={handleStep0Upload}
        onResumeChoice={handleResumeChoice}
        hasAnalyze={!!onAnalyze}
        hasTailor={!!onTailor}
        hasImportToEditor={!!onImportToEditor}
      />
    );
  }

  if (step === 1) {
    return (
      <div className="max-w-5xl mx-auto space-y-8 animate-in fade-in duration-300">
        <div className="text-center mb-8">
          <div className="flex items-center justify-center gap-3 mb-4">
            <button onClick={() => dispatch({ type: "SET_STEP", payload: 0 })} style={{ width: 36, height: 36, borderRadius: "50%", background: "var(--muted)", border: "1px solid var(--border)", cursor: "pointer", display: "flex", alignItems: "center", justifyContent: "center", color: "var(--muted-foreground)" }}>
              <ArrowLeft className="w-4 h-4" />
            </button>
            <h2 className="font-display text-3xl font-semibold" style={{ color: "var(--foreground)" }}>Choose a template</h2>
          </div>
          <p className="mt-2 text-sm" style={{ color: "var(--muted-foreground)" }}>Click a template to continue.</p>
        </div>
        <TemplatePicker
          state={templatePickerState}
          dispatch={dispatch}
          onSelect={(templateId) => { dispatch({ type: "SET_TEMPLATE", payload: templateId }); dispatch({ type: "SET_STEP", payload: 2 }); }}
        />
      </div>
    );
  }

  return (
    <div ref={formRootRef} className="w-full mx-auto max-w-4xl animate-in slide-in-from-right-4 duration-300" style={{ background: "var(--card)", border: "1px solid var(--border)", borderRadius: 24, overflow: "hidden" }}>
      <div style={{ padding: "28px 32px 20px", borderBottom: "1px solid var(--border)", position: "relative", textAlign: "center" }}>
        <button onClick={() => dispatch({ type: "SET_STEP", payload: 1 })} style={{ position: "absolute", left: 20, top: 24, width: 36, height: 36, borderRadius: "50%", background: "var(--muted)", border: "1px solid var(--border)", cursor: "pointer", display: "flex", alignItems: "center", justifyContent: "center", color: "var(--muted-foreground)" }}>
          <ArrowLeft className="w-4 h-4" />
        </button>
        <h2 className="font-display text-2xl font-semibold mt-1" style={{ color: "var(--foreground)" }}>Fill in your details</h2>
        <p style={{ fontSize: 14, color: "var(--muted-foreground)", marginTop: 4 }}>We'll use this to draft your resume</p>
      </div>

      <div style={{ padding: "28px 32px" }}>
        {/* Draft restore banner */}
        {hasDraft && !draftBannerDismissed && (
          <div className="flex items-center justify-between gap-3 mb-5 px-4 py-3 rounded-xl text-sm" style={{ background: "rgba(47,107,79,0.08)", border: "1px solid rgba(47,107,79,0.25)", color: "var(--forest)" }}>
            <div className="flex items-center gap-2">
              <Bookmark className="w-4 h-4 shrink-0" />
              <span>You have an unsaved draft — resume where you left off?</span>
            </div>
            <div className="flex gap-2 shrink-0">
              <button type="button" onClick={restoreDraft} style={{ fontSize: 12, fontWeight: 700, padding: "4px 10px", borderRadius: 8, background: "rgba(47,107,79,0.15)", border: "none", cursor: "pointer", color: "var(--forest)", fontFamily: "inherit" }}>Resume draft</button>
              <button type="button" onClick={() => { dispatch({ type: "SET_DRAFT_BANNER_DISMISSED", payload: true }); dispatch({ type: "SET_HAS_DRAFT", payload: false }); try { localStorage.removeItem(DRAFT_KEY); } catch {} }} style={{ fontSize: 12, fontWeight: 600, padding: "4px 8px", borderRadius: 8, background: "transparent", border: "none", cursor: "pointer", color: "var(--muted-foreground)", fontFamily: "inherit" }}>Dismiss</button>
            </div>
          </div>
        )}

        {/* Profile pre-fill banner */}
        {profileWasUsed && !profileBannerDismissed && (
          <div className="flex items-center justify-between gap-3 mb-5 px-4 py-3 rounded-xl text-sm" style={{ background: "rgba(217,119,87,0.07)", border: "1px solid rgba(217,119,87,0.20)", color: "var(--primary)" }}>
            <div className="flex items-center gap-2">
              <CheckCircle2 className="w-4 h-4 shrink-0" />
              <span>We pre-filled this form from your profile. Review and adjust anything before generating.</span>
            </div>
            <button type="button" onClick={() => dispatch({ type: "SET_PROFILE_BANNER_DISMISSED", payload: true })} style={{ background: "none", border: "none", cursor: "pointer", color: "var(--primary)", padding: 0, flexShrink: 0 }}>
              <X className="w-4 h-4" />
            </button>
          </div>
        )}
        {!profileWasUsed && !loading && (
          <div className="flex items-center gap-2 mb-5 px-4 py-3 rounded-xl text-sm" style={{ background: "rgba(232,185,72,0.08)", border: "1px solid rgba(232,185,72,0.20)", color: "var(--highlight)" }}>
            <Info className="w-4 h-4 shrink-0" />
            <span>Your profile is empty — fill in the fields below, or <a href="/profile" style={{ fontWeight: 700, textDecoration: "underline", color: "inherit" }}>complete your profile first</a> to auto-fill everything.</span>
          </div>
        )}

        <ImportSection
          state={importSectionState}
          dispatch={dispatch}
          onFileUpload={handleFileUpload}
          onImport={handleImport}
        />

        {/* Guidance tip */}
        <div style={{ marginBottom: 32, padding: 20, background: "rgba(232,185,72,0.08)", border: "1px solid rgba(232,185,72,0.25)", borderRadius: 16 }}>
          <div style={{ fontSize: 12, fontWeight: 700, color: "var(--highlight)", marginBottom: 10, display: "flex", alignItems: "center", gap: 6 }}>
            <Sparkles className="w-3.5 h-3.5" /> How to get the best results
          </div>
          <div className="grid grid-cols-1 md:grid-cols-2 gap-5">
            <div>
              <div style={{ fontSize: 11, fontWeight: 700, textTransform: "uppercase", letterSpacing: "0.1em", color: "var(--muted-foreground)", marginBottom: 6 }}>What happens next?</div>
              <p style={{ fontSize: 13, color: "var(--foreground)", lineHeight: 1.6 }}>After you submit, we'll open a <strong>Resume Workspace</strong>. You'll see your AI-generated resume and a live chat to refine it until it's perfect.</p>
            </div>
            <div>
              <div style={{ fontSize: 11, fontWeight: 700, textTransform: "uppercase", letterSpacing: "0.1em", color: "var(--muted-foreground)", marginBottom: 6 }}>Pro Tips</div>
              <ul style={{ fontSize: 13, color: "var(--foreground)", lineHeight: 1.7, paddingLeft: 16, listStyle: "disc" }}>
                <li><strong>Be specific</strong> — more detail = better AI output.</li>
                <li><strong>Blank is OK</strong> — AI generates bullets from job title.</li>
                <li><strong>Include skills</strong> — ensures the template highlights your stack.</li>
              </ul>
            </div>
          </div>
        </div>

        <form onSubmit={handleSubmit} style={{ display: "flex", flexDirection: "column", gap: 36 }}>
          <PersonalInfoSection state={personalInfoState} dispatch={dispatch} />
          <WorkHistorySection state={workHistoryState} dispatch={dispatch} />
          <EducationSection state={educationState} dispatch={dispatch} />
          <SkillsSection state={skillsState} dispatch={dispatch} />

          {/* Target Job Description */}
          <div>
            <div style={{ fontSize: 15, fontWeight: 600, color: "var(--foreground)", paddingBottom: 12, marginBottom: 16, borderBottom: "1px solid var(--border)", display: "flex", alignItems: "center", gap: 8 }}>
              <span>Target Job Description</span>
              <span style={{ fontSize: 11, fontWeight: 500, color: "var(--muted-foreground)", marginLeft: 4 }}>(optional)</span>
            </div>
            <p style={{ fontSize: 13, color: "var(--muted-foreground)", marginBottom: 10, lineHeight: 1.5 }}>Paste the job description you're applying for. We'll tailor your resume's keywords and bullets to match it.</p>
            <Textarea placeholder="Paste the job description here…" className="min-h-[120px] resize-y" style={{ background: "var(--muted)", border: "1px solid var(--border)", borderRadius: 12, padding: "10px 14px", fontSize: 13, color: "var(--foreground)", width: "100%" }} value={jobDescription} onChange={(e) => dispatch({ type: "SET_JOB_DESCRIPTION", payload: e.target.value })} />
          </div>

          <div style={{ paddingTop: 20, borderTop: "1px solid var(--border)" }}>
            <button type="submit" disabled={isGenerating} style={{ width: "100%", height: 52, background: isGenerating ? "var(--muted-foreground)" : "var(--foreground)", border: "none", borderRadius: 14, fontFamily: "inherit", fontSize: 15, fontWeight: 600, color: "var(--background)", cursor: isGenerating ? "not-allowed" : "pointer", display: "flex", alignItems: "center", justifyContent: "center", gap: 8, transition: "background 0.2s" }}>
              {isGenerating ? <><Loader2 className="w-5 h-5 animate-spin" /> Drafting your resume…</> : <><Sparkles className="w-5 h-5" /> Generate Resume Workspace</>}
            </button>
          </div>
        </form>
      </div>
    </div>
  );
}
