export interface WorkEntry {
  company: string;
  role: string;
  startDate: string;
  endDate: string;
  responsibilities: string;
  current: boolean;
}

export interface EducationEntry {
  university: string;
  degree: string;
  graduationYear: string;
  major: string;
  minor: string;
}

export interface PersonalInfo {
  name: string;
  email: string;
  phone: string;
  linkedin: string;
  github: string;
  portfolio: string;
}

export interface ResumeFormState {
  step: 0 | 1 | 2;
  startMethod: "scratch" | "linkedin" | "resume" | null;
  template: string;
  targetRoleSelect: string;
  targetRole: string;
  personalInfo: PersonalInfo;
  workHistory: WorkEntry[];
  education: EducationEntry[];
  skills: string[];
  newSkill: string;
  jobDescription: string;
  profileBannerDismissed: boolean;
  profileWasUsed: boolean;
  autoGeneratedEntries: number[];
  autoGeneratingEntries: number[];
  isGeneratingBullets: number | null;
  showImport: boolean;
  importText: string;
  importType: "linkedin" | "resume";
  isImporting: boolean;
  importError: string | null;
  expandedWorkIndices: number[];
  expandedEduIndices: number[];
  suggestedSkills: string[];
  draftBannerDismissed: boolean;
  hasDraft: boolean;
  uploadedResumeText: string;
  uploadedFileName: string;
  step0Uploading: "linkedin" | "resume" | null;
  step0Error: string | null;
  step0ResumeUploaded: { text: string; fileName: string; file: File } | null;
  processingChoice: "analyze" | "tailor" | "editor" | null;
}

export type ResumeFormAction =
  | { type: "SET_STEP"; payload: 0 | 1 | 2 }
  | { type: "SET_START_METHOD"; payload: "scratch" | "linkedin" | "resume" | null }
  | { type: "SET_TEMPLATE"; payload: string }
  | { type: "SET_TARGET_ROLE_SELECT"; payload: string }
  | { type: "SET_TARGET_ROLE"; payload: string }
  | { type: "SET_PERSONAL_INFO"; payload: Partial<PersonalInfo> }
  | { type: "SET_WORK_HISTORY"; payload: WorkEntry[] }
  | { type: "SET_EDUCATION"; payload: EducationEntry[] }
  | { type: "SET_SKILLS"; payload: string[] }
  | { type: "SET_NEW_SKILL"; payload: string }
  | { type: "SET_JOB_DESCRIPTION"; payload: string }
  | { type: "SET_PROFILE_BANNER_DISMISSED"; payload: boolean }
  | { type: "SET_PROFILE_WAS_USED"; payload: boolean }
  | { type: "SET_AUTO_GENERATED_ENTRIES"; payload: number[] }
  | { type: "SET_AUTO_GENERATING_ENTRIES"; payload: number[] }
  | { type: "SET_IS_GENERATING_BULLETS"; payload: number | null }
  | { type: "SET_SHOW_IMPORT"; payload: boolean }
  | { type: "SET_IMPORT_TEXT"; payload: string }
  | { type: "SET_IMPORT_TYPE"; payload: "linkedin" | "resume" }
  | { type: "SET_IS_IMPORTING"; payload: boolean }
  | { type: "SET_IMPORT_ERROR"; payload: string | null }
  | { type: "SET_EXPANDED_WORK_INDICES"; payload: number[] }
  | { type: "SET_EXPANDED_EDU_INDICES"; payload: number[] }
  | { type: "SET_SUGGESTED_SKILLS"; payload: string[] }
  | { type: "SET_DRAFT_BANNER_DISMISSED"; payload: boolean }
  | { type: "SET_HAS_DRAFT"; payload: boolean }
  | { type: "SET_UPLOADED_RESUME_TEXT"; payload: string }
  | { type: "SET_UPLOADED_FILE_NAME"; payload: string }
  | { type: "SET_STEP0_UPLOADING"; payload: "linkedin" | "resume" | null }
  | { type: "SET_STEP0_ERROR"; payload: string | null }
  | {
      type: "SET_STEP0_RESUME_UPLOADED";
      payload: { text: string; fileName: string; file: File } | null;
    }
  | { type: "SET_PROCESSING_CHOICE"; payload: "analyze" | "tailor" | "editor" | null };

export function makeInitialState(profile: {
  targetRole?: string | null;
  fullName?: string | null;
  email?: string | null;
  phone?: string | null;
  linkedin?: string | null;
  github?: string | null;
  portfolio?: string | null;
  workHistory?: Array<{
    company: string;
    role: string;
    startDate: string;
    endDate: string;
    responsibilities: string;
    current?: boolean;
  }> | null;
  education?: Array<{
    university: string;
    degree: string;
    graduationYear: string;
    major?: string | null;
    minor?: string | null;
  }> | null;
  skills?: string[] | null;
}): ResumeFormState {
  return {
    step: 0,
    startMethod: null,
    template: "Modern & Clean",
    targetRoleSelect: profile.targetRole ? "Other" : "",
    targetRole: profile.targetRole ?? "",
    personalInfo: {
      name: profile.fullName ?? "",
      email: profile.email ?? "",
      phone: profile.phone ?? "",
      linkedin: profile.linkedin ?? "",
      github: profile.github ?? "",
      portfolio: profile.portfolio ?? "",
    },
    workHistory: profile.workHistory?.length
      ? profile.workHistory.map(
          ({ company, role, startDate, endDate, responsibilities, current }) => ({
            company,
            role,
            startDate,
            endDate,
            responsibilities,
            current: Boolean(current),
          }),
        )
      : [
          {
            company: "",
            role: "",
            startDate: "",
            endDate: "",
            responsibilities: "",
            current: false,
          },
        ],
    education: profile.education?.length
      ? profile.education.map(({ university, degree, graduationYear, major, minor }) => ({
          university,
          degree,
          graduationYear,
          major: major ?? "",
          minor: minor ?? "",
        }))
      : [{ university: "", degree: "", graduationYear: "", major: "", minor: "" }],
    skills: profile.skills ?? [],
    newSkill: "",
    jobDescription: "",
    profileBannerDismissed: false,
    profileWasUsed: false,
    autoGeneratedEntries: [],
    autoGeneratingEntries: [],
    isGeneratingBullets: null,
    showImport: false,
    importText: "",
    importType: "linkedin",
    isImporting: false,
    importError: null,
    expandedWorkIndices: [0],
    expandedEduIndices: [0],
    suggestedSkills: [],
    draftBannerDismissed: false,
    hasDraft: false,
    uploadedResumeText: "",
    uploadedFileName: "",
    step0Uploading: null,
    step0Error: null,
    step0ResumeUploaded: null,
    processingChoice: null,
  };
}

export function resumeFormReducer(
  state: ResumeFormState,
  action: ResumeFormAction,
): ResumeFormState {
  switch (action.type) {
    case "SET_STEP":
      return { ...state, step: action.payload };
    case "SET_START_METHOD":
      return { ...state, startMethod: action.payload };
    case "SET_TEMPLATE":
      return { ...state, template: action.payload };
    case "SET_TARGET_ROLE_SELECT":
      return { ...state, targetRoleSelect: action.payload };
    case "SET_TARGET_ROLE":
      return { ...state, targetRole: action.payload };
    case "SET_PERSONAL_INFO":
      return { ...state, personalInfo: { ...state.personalInfo, ...action.payload } };
    case "SET_WORK_HISTORY":
      return { ...state, workHistory: action.payload };
    case "SET_EDUCATION":
      return { ...state, education: action.payload };
    case "SET_SKILLS":
      return { ...state, skills: action.payload };
    case "SET_NEW_SKILL":
      return { ...state, newSkill: action.payload };
    case "SET_JOB_DESCRIPTION":
      return { ...state, jobDescription: action.payload };
    case "SET_PROFILE_BANNER_DISMISSED":
      return { ...state, profileBannerDismissed: action.payload };
    case "SET_PROFILE_WAS_USED":
      return { ...state, profileWasUsed: action.payload };
    case "SET_AUTO_GENERATED_ENTRIES":
      return { ...state, autoGeneratedEntries: action.payload };
    case "SET_AUTO_GENERATING_ENTRIES":
      return { ...state, autoGeneratingEntries: action.payload };
    case "SET_IS_GENERATING_BULLETS":
      return { ...state, isGeneratingBullets: action.payload };
    case "SET_SHOW_IMPORT":
      return { ...state, showImport: action.payload };
    case "SET_IMPORT_TEXT":
      return { ...state, importText: action.payload };
    case "SET_IMPORT_TYPE":
      return { ...state, importType: action.payload };
    case "SET_IS_IMPORTING":
      return { ...state, isImporting: action.payload };
    case "SET_IMPORT_ERROR":
      return { ...state, importError: action.payload };
    case "SET_EXPANDED_WORK_INDICES":
      return { ...state, expandedWorkIndices: action.payload };
    case "SET_EXPANDED_EDU_INDICES":
      return { ...state, expandedEduIndices: action.payload };
    case "SET_SUGGESTED_SKILLS":
      return { ...state, suggestedSkills: action.payload };
    case "SET_DRAFT_BANNER_DISMISSED":
      return { ...state, draftBannerDismissed: action.payload };
    case "SET_HAS_DRAFT":
      return { ...state, hasDraft: action.payload };
    case "SET_UPLOADED_RESUME_TEXT":
      return { ...state, uploadedResumeText: action.payload };
    case "SET_UPLOADED_FILE_NAME":
      return { ...state, uploadedFileName: action.payload };
    case "SET_STEP0_UPLOADING":
      return { ...state, step0Uploading: action.payload };
    case "SET_STEP0_ERROR":
      return { ...state, step0Error: action.payload };
    case "SET_STEP0_RESUME_UPLOADED":
      return { ...state, step0ResumeUploaded: action.payload };
    case "SET_PROCESSING_CHOICE":
      return { ...state, processingChoice: action.payload };
    default:
      return state;
  }
}
