import React from "react";
import { ComboInput } from "@/components/ui/ComboInput";
import { MonthYearPicker } from "@/components/ui/MonthYearPicker";
import { EndDateField } from "@/components/ui/EndDateField";
import { endDateLabel } from "@/lib/workExperience";
import { JOB_TITLES, SP500_COMPANIES } from "@/lib/profileOptions";
import { Plus, Trash2, Loader2, Wand2 } from "lucide-react";
import { Textarea } from "@/components/ui/textarea";
import { suggestWorkExperienceBullets } from "@/services/geminiService";
import { ResumeFormState, ResumeFormAction, WorkEntry } from "./resumeFormReducer";

const fieldStyle: React.CSSProperties = {
  background: "var(--muted)",
  border: "1px solid var(--border)",
  borderRadius: 12,
  height: 48,
  fontSize: 14,
  padding: "0 14px",
  color: "var(--foreground)",
  width: "100%",
  outline: "none",
  fontFamily: "inherit",
};

const labelStyle: React.CSSProperties = {
  fontSize: 13,
  fontWeight: 600,
  color: "var(--foreground)",
  marginBottom: 6,
  display: "block",
};

const sectionHeadStyle: React.CSSProperties = {
  fontSize: 15,
  fontWeight: 600,
  color: "var(--foreground)",
  paddingBottom: 12,
  marginBottom: 16,
  borderBottom: "1px solid var(--border)",
  display: "flex",
  alignItems: "center",
  gap: 8,
};

const entryCardStyle: React.CSSProperties = {
  padding: 20,
  border: "1px solid var(--border)",
  borderRadius: 16,
  background: "var(--muted)",
  marginBottom: 16,
};

interface Props {
  state: Pick<
    ResumeFormState,
    | "workHistory"
    | "expandedWorkIndices"
    | "autoGeneratedEntries"
    | "autoGeneratingEntries"
    | "isGeneratingBullets"
    | "targetRole"
    | "targetRoleSelect"
  >;
  dispatch: React.Dispatch<ResumeFormAction>;
}

export const WorkHistorySection = React.memo(function WorkHistorySection({
  state,
  dispatch,
}: Props) {
  const {
    workHistory,
    expandedWorkIndices,
    autoGeneratedEntries,
    autoGeneratingEntries,
    isGeneratingBullets,
    targetRole,
    targetRoleSelect,
  } = state;

  const handleWorkChange = (index: number, field: string, value: string | boolean) => {
    const newWork = [...workHistory];
    newWork[index] = { ...newWork[index], [field]: value };
    dispatch({ type: "SET_WORK_HISTORY", payload: newWork });
  };

  const handleSuggestBullets = async (index: number) => {
    const work = workHistory[index];
    if (!work.role) return;
    dispatch({ type: "SET_IS_GENERATING_BULLETS", payload: index });
    try {
      const suggestions = await suggestWorkExperienceBullets(work.role, work.company);
      const newWork = [...workHistory];
      const currentText = newWork[index].responsibilities;
      newWork[index] = {
        ...newWork[index],
        responsibilities: currentText ? currentText + "\n\n" + suggestions : suggestions,
      };
      dispatch({ type: "SET_WORK_HISTORY", payload: newWork });
      dispatch({
        type: "SET_AUTO_GENERATED_ENTRIES",
        payload: autoGeneratedEntries.filter((i) => i !== index),
      });
    } catch (err) {
      console.error("Failed to generate bullets:", err);
    } finally {
      dispatch({ type: "SET_IS_GENERATING_BULLETS", payload: null });
    }
  };

  const addWork = () => {
    const newIdx = workHistory.length;
    dispatch({
      type: "SET_WORK_HISTORY",
      payload: [
        ...workHistory,
        { company: "", role: "", startDate: "", endDate: "", responsibilities: "", current: false },
      ],
    });
    dispatch({ type: "SET_EXPANDED_WORK_INDICES", payload: [...expandedWorkIndices, newIdx] });
  };

  const removeWork = (index: number) => {
    dispatch({ type: "SET_WORK_HISTORY", payload: workHistory.filter((_, i) => i !== index) });
    dispatch({
      type: "SET_EXPANDED_WORK_INDICES",
      payload: expandedWorkIndices.filter((i) => i !== index).map((i) => (i > index ? i - 1 : i)),
    });
  };

  return (
    <div>
      <div style={{ ...sectionHeadStyle, justifyContent: "space-between" }}>
        <span>Work History</span>
        <button
          type="button"
          onClick={addWork}
          style={{
            height: 32,
            padding: "0 12px",
            background: "var(--muted)",
            border: "1px solid var(--border)",
            borderRadius: 9999,
            fontFamily: "inherit",
            fontSize: 12,
            fontWeight: 600,
            cursor: "pointer",
            display: "flex",
            alignItems: "center",
            gap: 6,
            color: "var(--foreground)",
          }}
        >
          <Plus className="w-3.5 h-3.5" /> Add Job
        </button>
      </div>
      {workHistory.map((work, idx) => {
        const isExpanded = expandedWorkIndices.includes(idx);
        const isComplete = !!(work.role && work.company);
        return (
          <div key={idx} style={entryCardStyle}>
            {isComplete && !isExpanded ? (
              <div className="flex items-center justify-between">
                <div>
                  <div style={{ fontSize: 13, fontWeight: 600, color: "var(--foreground)" }}>
                    {work.role} {work.company ? `@ ${work.company}` : ""}
                  </div>
                  {(work.startDate || work.endDate || work.current) && (
                    <div style={{ fontSize: 11, color: "var(--muted-foreground)", marginTop: 2 }}>
                      {work.startDate || "?"} – {endDateLabel(work) || "Present"}
                    </div>
                  )}
                </div>
                <div className="flex items-center gap-2">
                  {workHistory.length > 1 && (
                    <button
                      type="button"
                      onClick={() => removeWork(idx)}
                      style={{
                        width: 28,
                        height: 28,
                        borderRadius: "50%",
                        background: "transparent",
                        border: "none",
                        cursor: "pointer",
                        display: "flex",
                        alignItems: "center",
                        justifyContent: "center",
                        color: "#e05c5c",
                      }}
                    >
                      <Trash2 className="w-3.5 h-3.5" />
                    </button>
                  )}
                  <button
                    type="button"
                    onClick={() =>
                      dispatch({
                        type: "SET_EXPANDED_WORK_INDICES",
                        payload: [...expandedWorkIndices, idx],
                      })
                    }
                    style={{
                      height: 28,
                      padding: "0 10px",
                      background: "var(--card)",
                      border: "1px solid var(--border)",
                      borderRadius: 8,
                      fontFamily: "inherit",
                      fontSize: 11,
                      fontWeight: 600,
                      cursor: "pointer",
                      color: "var(--foreground)",
                    }}
                  >
                    Edit
                  </button>
                </div>
              </div>
            ) : (
              <>
                <div
                  style={{
                    display: "flex",
                    justifyContent: "space-between",
                    alignItems: "center",
                    marginBottom: 16,
                  }}
                >
                  <span style={{ fontSize: 13, fontWeight: 600, color: "var(--muted-foreground)" }}>
                    Position #{idx + 1}
                  </span>
                  <div className="flex items-center gap-2">
                    {isComplete && (
                      <button
                        type="button"
                        onClick={() =>
                          dispatch({
                            type: "SET_EXPANDED_WORK_INDICES",
                            payload: expandedWorkIndices.filter((i) => i !== idx),
                          })
                        }
                        style={{
                          height: 28,
                          padding: "0 10px",
                          background: "var(--muted)",
                          border: "1px solid var(--border)",
                          borderRadius: 8,
                          fontFamily: "inherit",
                          fontSize: 11,
                          fontWeight: 600,
                          cursor: "pointer",
                          color: "var(--muted-foreground)",
                        }}
                      >
                        Collapse
                      </button>
                    )}
                    {workHistory.length > 1 && (
                      <button
                        type="button"
                        onClick={() => removeWork(idx)}
                        style={{
                          width: 32,
                          height: 32,
                          borderRadius: "50%",
                          background: "transparent",
                          border: "none",
                          cursor: "pointer",
                          display: "flex",
                          alignItems: "center",
                          justifyContent: "center",
                          color: "#e05c5c",
                        }}
                      >
                        <Trash2 className="w-4 h-4" />
                      </button>
                    )}
                  </div>
                </div>
                <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                  <div>
                    <label style={labelStyle}>
                      Job Title / Role <span style={{ color: "#e05c5c" }}>*</span>
                    </label>
                    <ComboInput
                      value={work.role}
                      onChange={(v) => handleWorkChange(idx, "role", v)}
                      options={JOB_TITLES}
                      placeholder="e.g., Software Engineer"
                      style={{ ...fieldStyle, background: "var(--card)" }}
                    />
                  </div>
                  <div>
                    <label style={labelStyle}>Company Name</label>
                    <ComboInput
                      value={work.company}
                      onChange={(v) => handleWorkChange(idx, "company", v)}
                      options={SP500_COMPANIES}
                      placeholder="e.g., Acme Corp"
                      style={{ ...fieldStyle, background: "var(--card)" }}
                    />
                  </div>
                  <div>
                    <label style={labelStyle}>Start Date</label>
                    <MonthYearPicker
                      value={work.startDate}
                      onChange={(v) => handleWorkChange(idx, "startDate", v)}
                      placeholder="Start date"
                      style={{
                        ...fieldStyle,
                        background: "var(--card)",
                        height: 48,
                        padding: "0 14px",
                      }}
                    />
                  </div>
                  <div>
                    <label style={labelStyle}>End Date</label>
                    <EndDateField
                      id={`resume-work-${idx}`}
                      endDate={work.endDate}
                      current={Boolean(work.current)}
                      onChange={({ endDate, current }) => {
                        const next = [...workHistory];
                        next[idx] = { ...next[idx], endDate, current };
                        dispatch({ type: "SET_WORK_HISTORY", payload: next });
                      }}
                      style={{
                        ...fieldStyle,
                        background: "var(--card)",
                        height: 48,
                        padding: "0 14px",
                      }}
                    />
                  </div>
                  <div style={{ gridColumn: "1 / -1" }}>
                    <div
                      style={{
                        display: "flex",
                        justifyContent: "space-between",
                        alignItems: "center",
                        marginBottom: 6,
                      }}
                    >
                      <div className="flex items-center gap-2">
                        <label style={{ ...labelStyle, marginBottom: 0 }}>
                          Responsibilities & Achievements
                        </label>
                        {autoGeneratedEntries.includes(idx) &&
                          !autoGeneratingEntries.includes(idx) && (
                            <span
                              style={{
                                fontSize: 10,
                                fontWeight: 600,
                                padding: "2px 7px",
                                borderRadius: 9999,
                                background: "rgba(47,107,79,0.10)",
                                color: "var(--forest)",
                                border: "1px solid rgba(47,107,79,0.20)",
                              }}
                            >
                              AI-generated — edit freely
                            </span>
                          )}
                        {autoGeneratingEntries.includes(idx) && (
                          <span
                            style={{
                              fontSize: 10,
                              color: "var(--muted-foreground)",
                              display: "flex",
                              alignItems: "center",
                              gap: 4,
                            }}
                          >
                            <Loader2 className="w-3 h-3 animate-spin" /> Auto-filling…
                          </span>
                        )}
                      </div>
                      <button
                        type="button"
                        disabled={
                          !work.role ||
                          isGeneratingBullets === idx ||
                          !(targetRoleSelect !== "Other" ? targetRoleSelect : targetRole)
                        }
                        onClick={() => handleSuggestBullets(idx)}
                        style={{
                          height: 28,
                          padding: "0 10px",
                          background: "rgba(217,119,87,0.10)",
                          border: "1px solid rgba(217,119,87,0.25)",
                          borderRadius: 8,
                          fontFamily: "inherit",
                          fontSize: 11,
                          fontWeight: 600,
                          cursor: "pointer",
                          display: "flex",
                          alignItems: "center",
                          gap: 5,
                          color: "var(--primary)",
                          opacity: !work.role || isGeneratingBullets === idx ? 0.5 : 1,
                        }}
                      >
                        {isGeneratingBullets === idx ? (
                          <>
                            <Loader2 className="w-3 h-3 animate-spin" /> Suggesting…
                          </>
                        ) : (
                          <>
                            <Wand2 className="w-3 h-3" /> Refresh bullets
                          </>
                        )}
                      </button>
                    </div>
                    <Textarea
                      placeholder="Describe your impact, scale, and technical stack used…"
                      className="min-h-[120px] resize-y"
                      style={{
                        background: "var(--card)",
                        border: "1px solid var(--border)",
                        borderRadius: 12,
                        padding: "10px 14px",
                        fontSize: 13,
                        color: "var(--foreground)",
                        width: "100%",
                      }}
                      value={work.responsibilities}
                      onChange={(e) => handleWorkChange(idx, "responsibilities", e.target.value)}
                    />
                  </div>
                </div>
              </>
            )}
          </div>
        );
      })}
    </div>
  );
});
