-- Shared cache for AI-generated market compensation data.
-- Keyed by a normalized role/location/yoe-tier string so the same query isn't
-- regenerated by the LLM on every request. Treated as shared reference data:
-- any authenticated user may read and upsert (no per-user ownership).
create table if not exists public.market_data_cache (
  cache_key text primary key,
  role text not null,
  location text not null,
  secondary_location text,
  yoe_tier text not null,
  data jsonb not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.market_data_cache enable row level security;

create policy market_cache_select on public.market_data_cache
  for select to authenticated using (true);

create policy market_cache_insert on public.market_data_cache
  for insert to authenticated with check (true);

create policy market_cache_update on public.market_data_cache
  for update to authenticated using (true) with check (true);
